### ISSUE TITLE
Create test UX enhancements

### ISSUE THREAD

**Issue by ITsvetkoFF** [ITsvetkoFF/Kv-012#124]
now to add test with one test step we shall delete the empty one. And we cannot easily add new test steps from keyboard. 

The proposition of UX enhancement is the next:
Imagine how cool the page will be when we will click on `Tab` button while being on the first test step expected result and the next step is created. So at first we will have only one step and create them on Tab key pressed.

But also we need some kind of a checkbox near the Add Test Step button like:
- [x] Use Tab to add  new steps

(so that user can choose if this feature is useful for him/her)

**Comment by ValeriiMal** [comment]
As for me the checkbox `Use Tab to add new steps` better to use in profile settings page for set this feature only ones. 
How do you think?

**Comment by vp9920** [comment]
I don't think it's so useful feature to disable this feature even in profile

**Comment by vp9920** [comment]
.... and if user often uses button to create new step, show notification in Toaster "You can use Tab key to create new step" and link "Got it, do not show anymore"

**Comment by ITsvetkoFF** [comment]
> and if user often uses button to create new step, show notification in Toaster "You can use Tab key to create new step" and link "Got it, do not show anymore"

this is the other solution, It is ok. I like it. the main point - is to explicitly explain user that tab is cool :)

About the setting in the profile - we can vote, as usual :)

**Comment by ValeriiMal** [comment]
I like vp9920's solution)
