### ISSUE TITLE
run execution page separate route 

### ISSUE THREAD

**Issue by ITsvetkoFF** [ITsvetkoFF/Kv-012#125]
proposition:
when we create test run the request to server is sent and server responds with the ID of created run. So the route will be: `/runs/:id/execute`

why?
0. This link can be sent to someone (and someone can open actual test run)
1. it helps not too loose the run (as soon as the run is created it can be associated to the creator and can be displayed on his/her dashboard). 
2. we can copy the contents of tests directly to test run model at the moment of creation. (it is good because the actual test case can be edited after creating test run and this fact can cause a lot of mess)

SO

- [ ] create route as follows: `/runs/:id/execute`
- [ ] inside execute run routing create one parent abstract route so that routes `/runs/:id/execute` and `/runs/:id/edit` can share some data over the parent route!

**Comment by ITsvetkoFF** [comment]
blocked till PR #109 is not merged

**Comment by OlehKSS** [comment]
there is no open PR#109 already
