### ISSUE TITLE
Merge Pull Request #98

### ISSUE THREAD

**Issue by ITsvetkoFF** [ITsvetkoFF/Kv-012#128]
Pull request with landing page #98

**Comment by ValeriiMal** [comment]
I merge PR #98 but it not working correctly on view and with login. 
When should I stop and what I have to do with this PR? Only view or handle all of the features with login?

**Comment by ITsvetkoFF** [comment]
You should make it work properly. Rewrite code if it is needed!

**Comment by ValeriiMal** [comment]
oh god

**Comment by vp9920** [comment]
wait, I'm preparing login implementation in mine user service, and I'm convinced that authorization service must be deleted, I have reasons for that

**Comment by ValeriiMal** [comment]
how can you implement login feature without anna's PR? If you want to implement login you should do this issue too... Let discus this tomorrow)

**Comment by vp9920** [comment]
that's not me who cannot implement my service without Ann's PR, that's you who cannot implement login without my service

**Comment by ValeriiMal** [comment]
@vp9920 , Let discus this tomorrow
