### ISSUE TITLE
More integration with Trello

### ISSUE THREAD

**Issue by ITsvetkoFF** [ITsvetkoFF/Kv-012#130]
- [ ] we shall create some boards with the project so that we can exchange more data:
            1. Backlog board. (It may be great to create the board with few columns(lists): defects, enhancements, tests, etc. This list ideally should be configurable from our side.) Overall this board is a set of tasks for developers, testers, ideas and so on. And it is a good practice do separate different items to different lists.
           2. Working board. Regular board with todo, in progress,to be tested, done. Also should be configurable from our side. Please consider that the next (not this!) task will be to create two types of projects: with and without sprints. 

- [ ] all tasks from the backlog board should be copied (constantly synchronized!?) with todo section of the regular board

**Comment by ValeriiMal** [comment]
@ITsvetkoFF in my opinion there are two convenient ways to configure project's dashboards:
- on creating point, configuration in the modal;
- on special page "manageProject" from navbar=>Team A=>Manage project.
As for me it will be good to include "Create default dashboards" checkbox in "Create project" modal (also checked by default) that allow aplication to create dashboards you wrote about. And other functionality for creating/deleting/managing dashboards/lists/cards etc. should be included to "Manage project" state.

What do you think about latter?

**Comment by ITsvetkoFF** [comment]
@ValeriiMal your solution may work :) So no config for the boards at the creation stage? But maybe two lines with [these](http://isteven.github.io/angular-multi-select/#/demo-horizontal-layout) elements for board lists(columns) in backlog and in working board.

**Comment by ValeriiMal** [comment]
@ITsvetkoFF It will be cool =) 
Ok, I wil try to use these feature in "Create project" modal for backlog and working boards.
