### ISSUE TITLE
Make css file less file (landing page)

### ISSUE THREAD

**Issue by annvaskovska** [ITsvetkoFF/Kv-012#99]
* we use less in main styles file
* we want to control our design efforts better (for example - see all used colors as variables at the beginning of our style file)

**Comment by ITsvetkoFF** [comment]
this issue is blocked till we will have landing page in master branch (till #98 will be megred)

**Comment by ITsvetkoFF** [comment]
styles are still css in your branch. And that issue with the font had place too
